name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_USER: '${{secrets.DOCKER_USER}}'
  DOCKER_PASSWORD: '${{secrets.DOCKER_PASSWORD}}'

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 'Action Docker Deployment'
    steps:
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2.10.0
      with:
        push: true
        tags: '${{ env.DOCKER_USER }}/gsdock:latest'  
