name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      env:
          DOCKER_USER: '${{secrets.DOCKER_USER}}'
          DOCKER_PASSWORD: '${{secrets.DOCKER_PASSWORD}}'
      with:
        username: $DOCKER_USER
        password: $DOCKER_PASSWORD
    - uses: docker/build-push-action@v2.10.0
      env:
          DOCKER_USER: '${{secrets.DOCKER_USER}}'
          DOCKER_PASSWORD: '${{secrets.DOCKER_PASSWORD}}'
      with:
        push: true
        tags: '${{secrets.DOCKER_USER}}/gsdock:latest'  
